site_name: FELIX-Filo docs
site_description: "User manual for the FELIX FIlo application"
site_author: "FELIX Robotics BV"
site_url: https://felixroboticsbv.github.io/FELIX-FILO-docs/
repo_name: "FELIX-FILO-docs"
use_directory_urls: true

plugins:
  - search
  - i18n:
      docs_structure: suffix # or "folder"
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: nl
          name: Netherlands
          build: true

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - admonition
  - pymdownx.details
  - pymdownx.superfences

copyright: <h3><i><u><a target="_blank" href="https://felixprinters.com/">© 2026 FELIX Robotics BV</a></u>. All Rights Reserved.

theme:
  name: material
  logo: assets/logo.png
  palette:
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: indigo
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to light mode
